validation:
  user:
    size:
      name: 50
      email: 255
      password: 6
    format:
      email: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
image:
  link_1: "https://rubyonrails.org/images/rails-logo.svg"
  link_2: "https://rubyonrails.org/"
session:
  remember: "1"
panigate:
  users: 10
time_active: 2
content: 140
image:
  file_image:  [image/jpeg, image/gif, image/png]
